package controllers;

import javafx.fxml.FXML;

import javafx.scene.control.ToggleGroup;

import javafx.event.ActionEvent;

public class informesController {
	@FXML
	private ToggleGroup informe;

	// Event Listener on Button.onAction
	@FXML
	public void aceptar(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void cancelar(ActionEvent event) {
		// TODO Autogenerated
	}
}
